import { test, expect } from '@playwright/test';

test('landing, account, projects, media and brand kit work at this viewport', async ({ page }, info) => {
  await page.route('**/api/auth/google/config', (route) => route.fulfill({ json: { configured: false, firebase: null } }));
  await page.route('**/api/chat', (route) => route.fulfill({ status: 503, json: { error: 'AI generation is disabled or incomplete. Configure GEMINI_API_KEY and GEMINI_MODEL before enabling generation.', code: 'AI_NOT_CONFIGURED' } }));
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Many sources. One creative direction.' })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: `tmp/landing-${info.project.name}.png`, fullPage: true });
  await page.getByRole('link', { name: 'Start creating' }).click();
  await expect(page.getByRole('button', { name: 'Continue with Google' })).toBeDisabled();
  await expect(page.getByText(/Google sign-in will be available/)).toBeVisible();
  await page.getByLabel('Your name').fill('Test Creator');
  await page.getByLabel('Email address').fill(`browser-${info.project.name}-${Date.now()}@example.com`);
  await page.getByLabel('Password').fill('BrowserPass123!');
  await page.getByRole('button', { name: 'Create account' }).click();
  await expect(page.getByRole('heading', { name: "Let's make something, Test." })).toBeVisible();
  await page.getByRole('button', { name: 'Create your first project' }).click();
  await page.getByLabel('Project name').fill('Browser campaign');
  await page.getByLabel('Brief', { exact: true }).fill('A calm and thoughtful creative launch.');
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'What are we creating today?' })).toBeVisible();
  await page.getByLabel('Upload media files').setInputFiles({ name: 'brief.txt', mimeType: 'text/plain', buffer: Buffer.from('We launch an independent studio this autumn.') });
  await expect(page.getByRole('button', { name: /brief.txt TEXT/ })).toBeVisible();
  await page.getByRole('button', { name: /brief.txt TEXT/ }).click();
  await expect(page.getByText('We launch an independent studio this autumn.')).toBeVisible();
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'Write a caption' }).click();
  await expect(page.getByLabel('Message CreatorForge')).toHaveValue(/Instagram captions/);
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByRole('alert')).toContainText('GEMINI_API_KEY');
  await page.getByRole('tab', { name: 'Content remix' }).click();
  await page.getByLabel('Source asset').selectOption({ label: 'brief.txt' });
  await expect(page.getByRole('button', { name: 'Generate remix' })).toBeEnabled();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: `tmp/workspace-${info.project.name}.png`, fullPage: true });
  await page.getByRole('link', { name: 'Brand kit' }).click();
  await page.getByLabel('Brand name', { exact: true }).fill('Independent Studio');
  await page.getByLabel('Tone of voice').fill('Thoughtful and warm');
  await page.getByLabel('Brand colors').fill('#8B5CF6, #10B981');
  await page.getByRole('button', { name: 'Save brand kit' }).click();
  await expect(page.getByRole('status')).toContainText('Brand kit saved');
  await page.reload();
  await expect(page.getByLabel('Brand name', { exact: true })).toHaveValue('Independent Studio');
  await page.getByRole('link', { name: 'Back to projects' }).click();
  await expect(page.getByRole('heading', { name: 'Browser campaign' })).toBeVisible();
  await page.screenshot({ path: `tmp/dashboard-${info.project.name}.png`, fullPage: true });
  await page.getByRole('button', { name: 'Delete Browser campaign' }).click();
  await page.getByRole('button', { name: 'Delete project', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Create your first project' })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  expect(errors).toEqual([]);
});
