import { test, expect } from '@playwright/test';

test('landing, account, projects, media and brand kit work at this viewport', async ({ page }, info) => {
  await page.route('**/api/auth/google/config', (route) => route.fulfill({ json: { configured: false, firebase: null } }));
  await page.route('**/api/chat/stream', (route) => route.fulfill({ status: 503, json: { error: 'AI generation is disabled or incomplete. Configure GEMINI_API_KEY and GEMINI_MODEL before enabling generation.', code: 'AI_NOT_CONFIGURED' } }));
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Turn raw research into publication-ready writing. Without losing your voice.' })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: `tmp/landing-${info.project.name}.png`, fullPage: true });
  await page.getByRole('link', { name: 'Start Writing Free' }).first().click();
  await expect(page.getByRole('button', { name: 'Continue with Google' })).toBeDisabled();
  await expect(page.getByText(/Google sign-in will be available/)).toBeVisible();
  await page.getByLabel('Your name').fill('Test Creator');
  await page.getByLabel('Email address').fill(`browser-${info.project.name}-${Date.now()}@example.com`);
  await page.getByLabel('Password').fill('BrowserPass123!');
  await page.getByRole('button', { name: 'Create account' }).click();
  await expect(page.getByRole('heading', { name: 'Editorial Desk · Test' })).toBeVisible();
  await page.getByRole('button', { name: 'Create your first project' }).click();
  await page.getByLabel('Project title').fill('Browser campaign');
  await page.getByLabel('Brief & focus').fill('A calm and thoughtful creative launch.');
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'What are we drafting today?' })).toBeVisible();
  await page.getByLabel('Upload media files').setInputFiles({ name: 'brief.txt', mimeType: 'text/plain', buffer: Buffer.from('We launch an independent studio this autumn.') });
  await expect(page.getByRole('button', { name: /brief.txt TEXT/ })).toBeVisible();
  await page.getByRole('button', { name: /brief.txt TEXT/ }).click();
  await expect(page.getByText('We launch an independent studio this autumn.')).toBeVisible();
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'Draft social thread' }).click();
  await expect(page.getByLabel('Message CreatorForge')).toHaveValue(/thread/);
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByRole('alert')).toContainText('GEMINI_API_KEY');
  await page.getByRole('tab', { name: 'Agent Studio' }).click();
  await page.getByLabel('Idea / source notes').fill('Develop a script from this campaign brief.');
  await expect(page.getByRole('button', { name: 'Create draft', exact: true })).toBeEnabled();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: `tmp/workspace-${info.project.name}.png`, fullPage: true });
  await page.getByRole('link', { name: 'Brand Manual' }).click();
  await page.getByLabel('Publication / Brand name', { exact: true }).fill('Independent Studio');
  await page.getByLabel('Voice & Register').fill('Thoughtful and warm');
  await page.getByLabel('Palette (Hex codes)').fill('#8B5CF6, #10B981');
  await page.getByRole('button', { name: 'Save brand manual' }).click();
  await expect(page.getByText(/Brand manual saved/)).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Publication / Brand name', { exact: true })).toHaveValue('Independent Studio');
  await page.getByRole('link', { name: 'Back to projects' }).click();
  await expect(page.getByRole('heading', { name: 'Browser campaign' })).toBeVisible();
  await page.screenshot({ path: `tmp/dashboard-${info.project.name}.png`, fullPage: true });
  await page.getByRole('button', { name: 'Delete Browser campaign' }).click();
  await page.getByRole('button', { name: 'Delete project', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Create your first project' })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page.getByRole('heading', { name: /Welcome back/i })).toBeVisible();
  expect(errors).toEqual([]);
});

