import { test, expect } from '@playwright/test';
import { mkdtemp, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import { createApp } from '../../server/src/app.js';
import { Message } from '../../server/src/models.js';

const root = fileURLToPath(new URL('../../', import.meta.url));
let directory;
let database;
let server;
let origin;
let provider;
let providerSignal;
let release;
test.beforeAll(async () => {
  directory = await mkdtemp(`${root}tmp/chat-stream-browser-`);
  database = await MongoMemoryServer.create({ instance: { dbPath: directory }, binary: { downloadDir: `${root}tmp/mongodb-binaries` } });
  await mongoose.connect(database.getUri(), { dbName: 'stream-browser-test' });
  server = createApp({ jwtSecret: 'browser-stream-test-secret-at-least-thirty-two-characters', aiEnabled: true, geminiModel: 'gemini-test-provider', generateContentStream: request => { providerSignal = request.config.abortSignal; return provider(request); } }).listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  origin = `http://127.0.0.1:${server.address().port}`;
});
test.afterEach(() => release?.());
test.afterAll(async () => {
  if (server) await new Promise(resolve => server.close(resolve));
  await mongoose.disconnect();
  if (database) await database.stop();
  if (directory) await rm(directory, { recursive: true, force: true });
});
async function workspace(page, info, label) {
  const account = await (await fetch(`${origin}/api/auth/register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: 'Stream Creator', email: `${label}-${info.project.name}@example.com`, password: 'BrowserTest123!' }) })).json();
  const headers = { Authorization: `Bearer ${account.token}`, 'Content-Type': 'application/json' };
  const project = await (await fetch(`${origin}/api/projects`, { method: 'POST', headers, body: JSON.stringify({ name: `Streaming ${label}` }) })).json();
  await page.route('**/api/**', async route => {
    const address = new URL(route.request().url());
    const target = `${origin}${address.pathname}${address.search}`;
    if (address.pathname === '/api/chat/stream') return route.continue({ url: target });
    const response = await route.fetch({ url: target });
    await route.fulfill({ response });
  });
  await page.addInitScript(token => localStorage.setItem('creatorforge.token', token), account.token);
  await page.goto(`/project/${project._id}`);
  await expect(page.getByLabel('Message CreatorForge')).toBeVisible();
  return project;
}
test('live draft appears before completion and only finished replies can be saved', async ({ page }, info) => {
  const gate = new Promise(resolve => { release = resolve; });
  provider = async function* () { yield '# Live draft\n\n'; await gate; yield 'Finished response ✨'; };
  const project = await workspace(page, info, 'complete');
  await page.getByLabel('Message CreatorForge').fill('Write a launch draft');
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByRole('heading', { name: 'Live draft' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Stop generation' })).toBeVisible();
  await expect(page.getByText('Draft · not saved yet')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Save response to library', exact: true })).toHaveCount(0);
  expect(await Message.countDocuments({ projectId: project._id })).toBe(0);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: `${root}tmp/streaming-${info.project.name}.png`, fullPage: true });
  release();
  await expect(page.getByRole('button', { name: 'Stop generation' })).toHaveCount(0);
  await expect(page.getByText('Finished response ✨', { exact: true })).toBeVisible();
  expect(await Message.countDocuments({ projectId: project._id })).toBe(2);
  await page.getByRole('button', { name: 'Save response to library', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Response saved to library', exact: true })).toBeDisabled();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Live draft' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Response saved to library', exact: true })).toBeDisabled();
});
test('Stop keeps the prompt, aborts upstream, saves nothing and allows retry', async ({ page }, info) => {
  let streamRequests = 0;
  page.on('request', request => { if (new URL(request.url()).pathname === '/api/chat/stream') streamRequests++; });
  const gate = new Promise(resolve => { release = resolve; });
  provider = async function* () { yield '# Cancelled draft'; await gate; yield '\nShould not save'; };
  const project = await workspace(page, info, 'stop');
  const input = page.getByLabel('Message CreatorForge');
  await input.fill('Keep this prompt');
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByRole('heading', { name: 'Cancelled draft' })).toBeVisible();
  const signal = providerSignal;
  await page.getByRole('button', { name: 'Stop generation' }).click();
  await expect(input).toBeEnabled();
  await expect(input).toHaveValue('Keep this prompt');
  await expect(page.getByRole('heading', { name: 'Cancelled draft' })).toHaveCount(0);
  await expect.poll(() => signal.aborted).toBe(true);
  expect(await Message.countDocuments({ projectId: project._id })).toBe(0);
  expect(streamRequests).toBe(1);
  release();
  provider = async function* () { yield '# Retry succeeded'; };
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByRole('button', { name: 'Stop generation' })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Retry succeeded' })).toBeVisible();
  await expect(input).toHaveValue('');
  expect(await Message.countDocuments({ projectId: project._id })).toBe(2);
  expect(streamRequests).toBe(2);
});
test('provider failure preserves app session and discards the draft', async ({ page }, info) => {
  provider = async function* () { yield 'Unsaved partial'; throw Object.assign(new Error('private provider credential'), { status: 401 }); };
  const project = await workspace(page, info, 'failure');
  await page.getByLabel('Message CreatorForge').fill('Try provider');
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByText(/Google denied generation access/)).toBeVisible();
  await expect(page.getByLabel('Message CreatorForge')).toBeEnabled();
  await expect(page.getByLabel('Message CreatorForge')).toHaveValue('Try provider');
  expect(page.url()).toContain(`/project/${project._id}`);
  expect(await page.evaluate(() => Boolean(localStorage.getItem('creatorforge.token')))).toBe(true);
  expect(await Message.countDocuments({ projectId: project._id })).toBe(0);
  await expect(page.getByText('Unsaved partial', { exact: true })).toHaveCount(0);
});
test('navigation aborts generation without leaking drafts into another workspace', async ({ page }, info) => {
  const gate = new Promise(resolve => { release = resolve; });
  provider = async function* () { yield '# Navigation draft'; await gate; yield 'Should not save'; };
  const project = await workspace(page, info, 'navigate');
  await page.getByLabel('Message CreatorForge').fill('Navigate away');
  await page.getByRole('button', { name: 'Send message' }).click();
  await expect(page.getByRole('heading', { name: 'Navigation draft' })).toBeVisible();
  const signal = providerSignal;
  await page.goto('/dashboard');
  await expect.poll(() => signal.aborted).toBe(true);
  release();
  await page.goto(`/project/${project._id}`);
  await expect(page.getByLabel('Message CreatorForge')).toBeEnabled();
  await expect(page.getByRole('heading', { name: 'Navigation draft' })).toHaveCount(0);
  expect(await Message.countDocuments({ projectId: project._id })).toBe(0);
});
